[misc] Use partial install from "make check" for examples/wily-guile.
* examples/wily-guile.in: Rewrite: Allow env var ‘GUILE’
override; check for partial install under ../source/;
don't set env var ‘GUILE_LOAD_PATH’; instead, mine
‘GUILE_SITE’ from ../source/Makefile and use it for ‘-L’ arg.

diff --git a/examples/wily-guile.in b/examples/wily-guile.in
--- a/examples/wily-guile.in
+++ b/examples/wily-guile.in
@@ -1,10 +1,13 @@
 #!/bin/sh
-guile="@GUILE@"
-exd="@abs_top_builddir@/examples"
-
-test -h "$exd/www" || ( cd "$exd" ; ln -s ../source www )
-
-GUILE_LOAD_PATH=`echo "$exd:$GUILE_LOAD_PATH" | sed 's/:$//'`
-export GUILE_LOAD_PATH
-
-exec $guile "$@"
+guile=${GUILE-"@GUILE@"}
+d=`dirname $0`
+d=`cd $d ; pwd`
+source=`echo $d | sed 's|examples$|source|'`
+prefix="$source/.fake"
+if ! test -d "$prefix" ; then
+    echo 'ERROR: No partial installation under source/'
+    echo 'Do "make check" from top build dir, first.'
+    exit 1
+fi
+eval `sed '/^GUILE_SITE *= */!d;s/ *= */=/' $source/Makefile`
+exec $guile -L "$GUILE_SITE" "$@"
